// LAN smoothness: a host walks a smooth path while acting twice a second; on the guest, the host's avatar must
// move without lurches (a frame step more than 1.5× the previous one) and frames must stay paced.
//   node tests/browser/lan-smooth.mjs <repo-root> [cpu-throttle]
import { chromium } from 'playwright-core'; import { spawn } from 'node:child_process'; import { mkdtempSync } from 'node:fs'; import os from 'node:os'; import path from 'node:path';
const [root, throttle] = process.argv.slice(2);
const server = spawn(process.execPath, ['lan/server.mjs'], { cwd: root, env: { ...process.env, PORT: '0', BIND: '127.0.0.1', ROOM_CODE: 'JNK001', HOST_KEY: 'hk', CAMPAIGN_SAVE: path.join(mkdtempSync(path.join(os.tmpdir(), 'jk-')), 's.json') }, stdio: ['ignore', 'pipe', 'pipe'] });
const base = await new Promise(r => server.stdout.on('data', d => { const m = /localhost:(\d+)/.exec(String(d)); if (m) r('http://127.0.0.1:' + m[1]); }));
const b = await chromium.launch({ executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', args: ['--use-angle=metal'] });
async function client(n) { const p = await (await b.newContext({ viewport: { width: 1280, height: 760 } })).newPage(); await p.addInitScript(n => { localStorage.setItem('infra-face', 'smile'); localStorage.setItem('infra-name', n); localStorage.setItem('infra-face-name', n); }, n); await p.goto(base + '/'); await p.waitForFunction(() => globalThis.__infra?.lab, null, { timeout: 60000 }); await p.waitForTimeout(1200); return p; }
const host = await client('Darja'); await host.click('[data-start=payday]'); await host.waitForTimeout(600); await host.click('#ss-pay-host'); await host.waitForTimeout(3000);
const guest = await client('Sam'); await guest.click('[data-start=join]'); await guest.fill('#ss-code', 'JNK001'); await guest.click('#ss-join'); await guest.waitForTimeout(3000);
if (throttle) { const c = await guest.context().newCDPSession(guest); await c.send('Emulation.setCPUThrottlingRate', { rate: +throttle }); }
await guest.evaluate(() => { __infra.lab.enter(); __infra.lab.look(0, 30, 0, 9, 0); });
// Host walks back and forth (moves its camera smoothly) and acts every 500 ms.
const walking = host.evaluate(async () => { __infra.lab.enter(); const c = __infra.camera, t0 = performance.now(); while (performance.now() - t0 < 6000) { const t = (performance.now() - t0) / 1000; c.position.set(Math.sin(t * 1.2) * 20, 9.7, 10); await new Promise(r => requestAnimationFrame(r)); } });
const acting = host.evaluate(async () => { for (let i = 0; i < 12; i++) { __infra.lab.casinoUI.send({ type: 'hello' }); __infra.lab.lan.send({ type: 'casino', action: { type: 'drink', drink: 'x' } }).catch(() => {}); await new Promise(r => setTimeout(r, 500)); } });
const res = await guest.evaluate(() => new Promise(res => { const ft = [], pos = []; let last = performance.now(); const t0 = last; const f = now => { ft.push(now - last); last = now; const m = [...(__infra.lab.lan.models || new Map()).values()][0]; if (m) pos.push(m.g.position.x); if (now - t0 < 5500) requestAnimationFrame(f); else { const s = [...ft].sort((a, b) => a - b); const steps = pos.slice(1).map((x, i) => Math.abs(x - pos[i])); const jerk = steps.slice(1).map((d, i) => Math.abs(d - steps[i])); res({ fps: Math.round(1000 / (ft.reduce((a, b) => a + b, 0) / ft.length)), p95: +s[Math.floor(s.length * .95)].toFixed(1), max: +s.at(-1).toFixed(1), lurches: steps.slice(30).filter((d, i) => d > .05 && d > steps.slice(30)[i - 1] * 1.5 + .02 && i > 0).length, sample: steps.slice(120, 140).map(x => +x.toFixed(2)).join(' '), stillFrames: steps.filter(d => d < 1e-4).length, frames: ft.length }); } }; requestAnimationFrame(f); }));
await walking; await acting; console.log(JSON.stringify(res)); const pass = res.lurches <= 5 && res.p95 < 34; /* the old chase-the-latest smoothing gave ~36 */ console.log(pass ? 'PASS LAN movement is smooth' : 'FAIL LAN movement'); await b.close(); server.kill(); process.exit(pass ? 0 : 1);
