import fs from 'node:fs';import {fileURLToPath,pathToFileURL} from 'node:url';import path from 'node:path';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');const assetRoot=fs.existsSync(path.join(root,'dist/index.html'))?path.join(root,'dist'):root;const asset=name=>pathToFileURL(path.join(assetRoot,name)).href;

globalThis.fetch=async()=>({ok:false,status:404});import assert from 'node:assert/strict';
class El{constructor(){this.style={};this.dataset={};this.hidden=false;this.classList={add(){},remove(){},toggle(){}};this.value='';this.options=[];this.selectedIndex=0;}set innerHTML(html){this._html=html;this.nav=null;for(const m of html.matchAll(/<(input|select|button|fieldset|output|pre|div)[^>]*\bid="([^"]+)"[^>]*>/g)){const e=document.getElementById(m[2]);e.value=/\bvalue="([^"]*)"/.exec(m[0])?.[1]||'';e.checked=/\bchecked\b/.test(m[0]);if(m[1]==='select'){const end=html.slice(m.index).indexOf('</select>'),body=html.slice(m.index,m.index+end),opts=[...body.matchAll(/<option value="([^"]*)"([^>]*)>/g)];e.value=(opts.find(o=>o[2].includes('selected'))||opts[0])?.[1]||'';}}if(html.includes('data-pg-page'))this.nav=[...html.matchAll(/data-pg-page="([^"]+)"/g)].map(m=>{const e=new El();e.dataset.pgPage=m[1];return e;});}get innerHTML(){return this._html||''}insertAdjacentHTML(_where,html){this.innerHTML=html;}replaceChildren(...items){this.options=items;this.value=items[0]?.value??'';}addEventListener(){}setAttribute(){}append(){}querySelectorAll(selector){if(this.nav)return this.nav;return selector==='[data-pg-page]'?[...(this._html||'').matchAll(/data-pg-page="([^"]+)"/g)].map(m=>{const e=new El();e.dataset.pgPage=m[1];return e;}):[]}querySelector(){return new El()}focus(){}remove(){}setPointerCapture(){}click(){this.onclick?.()}getContext(){return {createRadialGradient(){return{addColorStop(){}}},fillRect(){},fillText(){}}}}
const slotButtons=[0,1,2].map(n=>{const e=new El();e.dataset.slot=String(n);e.textContent=n?n+' Empty':'0 Hands';return e;});const els=new Map();globalThis.Option=class{constructor(text,value){this.text=text;this.value=String(value)}};globalThis.document={addEventListener(){},getElementById(id){if(!els.has(id))els.set(id,new El());return els.get(id)},querySelector(){return new El()},querySelectorAll(sel){return sel==='[data-slot]'?slotButtons:[]},createElement(){return new El()},body:new El(),hidden:false};
const listeners={};
Object.assign(globalThis,{innerWidth:1440,innerHeight:900,devicePixelRatio:1,matchMedia:()=>({matches:false}),addEventListener(type,fn){(listeners[type]??=[]).push(fn)},requestAnimationFrame(){}});
globalThis.MockRenderer=class{setPixelRatio(){}setSize(){}setClearColor(){}getPixelRatio(){return 1}render(){}};
const THREE=await import(asset('three.module.js'));globalThis.MockControls=class{constructor(camera){this.camera=camera;this.target=new THREE.Vector3();this.mouseButtons={LEFT:0}}addEventListener(){}update(){this.camera.lookAt(this.target)}};
let src=fs.readFileSync(path.join(assetRoot,'app.js'),'utf8').replace("import { OrbitControls } from './OrbitControls.js';","const OrbitControls=globalThis.MockControls;").replace('new THREE.WebGLRenderer(','new globalThis.MockRenderer(');
src=src.replace(/from '\.\/([^']+)'/g,(_,name)=>"from '"+asset(name)+"'");
src+='\nglobalThis.testApp={lab,pickables,state,nodes,links,byId,racks,selectLayer,simulate,restoreAll,command,animate,chooseDevice,chooseLink,zoomBy,camera,orbitControls,setCamera,goalTarget,goalCamera,scene};';
await import('data:text/javascript;base64,'+Buffer.from(src).toString('base64'));export const a=globalThis.testApp;
