// Contract 1 as a live task chain: each real action advances "next step"; the contract is accepted
// automatically by the host tick when the employee Internet test passes, and contract 2 appears.
import assert from 'node:assert/strict';
import { a } from './app-harness.mjs';
import { helpers } from './build-helpers.mjs';
import { contractSteps } from '../dist/contract-steps.js';
const h = helpers(a), { w, office, config, install, op } = h, o = w.office, s = () => o.state, net = a.lab.kit.network;
const next = () => contractSteps(o, net, a.nodes).steps.find(x => !x.ok)?.label;
const seen = [];
const expectNext = label => { const n = next(); assert.equal(n, label, 'next step'); seen.push(n); };
h.engineering({ type: 'mode', mode: 'campaign', enterprise: true });
expectNext('Order a FortiGate and an access switch');
const sw = install('fs148f', { racks: ['R01'] }), fw = install('fg200f', { racks: ['R02'] });
expectNext('Initialize the switch on its serial console');
const consoleSession = { node: sw, config: false };
for (const cmd of ['config system interface', 'edit mgmt', 'set ip 10.10.70.8/24', 'set allowaccess ping https ssh', 'next', 'end']) await net.command(cmd, consoleSession);
expectNext('Assign gateway and access switch');
await office({ type: 'login', user: 'itadmin', password: 'OfficeLab19!' });
await office({ type: 'configure', page: 'binding', value: { access: sw.id, firewall: fw.id, floor: 1, port: 0, fwPort: 0, ispPlan: 'fiber30' } });
expectNext('Provider router racked, powered and patched to WAN');
h.installISP(fw, 'port3', { racks: ['R03'] });
expectNext('WAN configured from the circuit sheet');
await office({ type: 'configure', page: 'wan', value: { port: 'port3', mode: 'static', defaultRoute: true, dnsForward: true } });
expectNext('VLAN 10 gateway interface and DHCP');
await office({ type: 'configure', page: 'interfaces', value: { id: 10, name: 'SALES', ip: '10.10.10.1', prefix: 24, enabled: true, zone: 'staff', mtu: 1500 } });
await office({ type: 'configure', page: 'dhcp', value: { id: 10, enabled: true, start: 100, end: 199, gateway: '10.10.10.1', dns: '10.10.10.1', lease: 3600 } });
expectNext('Sales desk patched to an access port in VLAN 10');
await office({ type: 'patch-pc', id: 'F1-sales-PC', port: 1 });
await office({ type: 'configure', page: 'switching', value: { ...s().ports['F1-sales-PC'], id: 'F1-sales-PC', vlan: 10, trunk: '10' } });
expectNext('VLAN 10 carried to the FortiGate');
config({ type: 'vlan', node: sw.id, id: 10 }); for (const n of [sw, fw]) config({ type: 'port', node: n.id, index: 0, value: { mode: 'trunk', allowed: [1, 10] } });
expectNext('LAN → WAN policy with source NAT');
await office({ type: 'configure', page: 'policies', value: { id: 'sales-out', src: '10', dst: 'wan', source: 'any', destination: 'any', service: 'any', action: 'accept', nat: true, enabled: true, start: 0, end: 24 } });
await office({ type: 'login', user: 'sales', pc: 'F1-sales-PC', password: 'OfficeLab19!' });
expectNext('Contract accepted');
const budget = op.game.budget; o.tick(Date.now() + 60000);
assert.equal(s().chapter, 1, 'contract accepted automatically by the host tick'); assert.equal(op.game.budget, budget + 15000);
assert.equal(contractSteps(o, net, a.nodes).title, 'Department segmentation', 'next contract is shown');
console.log('PASS: contract chain · ' + seen.length + ' live next-step transitions, automatic acceptance and payment, next contract shown.');
process.exit(0);
