import assert from 'node:assert/strict';
import {existsSync} from 'node:fs';
const assets=new URL(existsSync(new URL('../dist/index.html',import.meta.url))?'../dist/':'../',import.meta.url);
const {createNetwork}=await import(new URL('network-sim.js',assets));
const {hostIdentifiers}=await import(new URL('product-config.js',assets));
const nodes=[],links=[],byId={};
function node(id,type,sku){const n={id,type,spec:{sku},model:sku,ports:[]};for(const [name,medium]of [['FC-A','Fibre Channel'],['FC-B','Fibre Channel'],['DATA-A','Ethernet'],['DATA-B','Ethernet'],['MGMT UPLINK','Ethernet']])n.ports.push({name,medium,speed:medium==='Ethernet'?25:32});nodes.push(n);byId[id]=n;return n;}
const host=node('HOST','server','r760'),store=node('ARRAY','storage','me5024fc'),fa=node('FAB-A','san','ds6610'),fb=node('FAB-B','san','ds6610'),ea=node('ETH-A','switch','dells5248'),eb=node('ETH-B','switch','dells5248'),fw=node('FW','firewall','fg200f');
const net=createNetwork({nodes,links,byId,isOffline:()=>false,refreshFaults:()=>{}}),cfg=(n,op,value)=>net.apply({type:'product',node:n.id,op,value});
const ids=hostIdentifiers(host),target=hostIdentifiers(store),base={protocol:'FC',portA:'FC-A',portB:'FC-B',mtu:1500,...ids,initiatorEnabled:true,os:'Linux',raid:'RAID 1 boot'};
assert.match(cfg(host,'host',base),/^Applied/);assert.match(cfg(store,'storage',{...base,pool:'POOL',mode:'Linear',raid:'ADAPT',volume:'VOL1',sizeGiB:100,host:host.id,initiator:ids.wwpnA}),/initial setup/,'provisioning waits for the array initial setup');assert.match(cfg(store,'identity',{name:'ARRAY-01',passwordChanged:true}),/^Applied/);assert.match(cfg(store,'storage',{...base,pool:'POOL',mode:'Linear',raid:'ADAPT',volume:'VOL1',sizeGiB:100,host:host.id,initiator:ids.wwpnA}),/^Applied/);
function link(a,ai,b,bi){const l={a:a.id,pa:a.ports[ai],b:b.id,pb:b.ports[bi]};links.push(l);l.pa.link=l;l.pb.link=l;return l;}
link(store,0,fa,0);link(fa,1,host,0);link(store,1,fb,0);const last=link(fb,1,host,1);
assert.equal(net.storagePaths(store).length,0,'no zoning');for(const [fabric,side]of [[fa,'A'],[fb,'B']])assert.match(cfg(fabric,'fabric',{aliases:{host:[ids['wwpn'+side]],target:[target['wwpn'+side]]},zones:{z:['host','target']},configs:{prod:['z']},members:[ids['wwpn'+side],target['wwpn'+side]],enabled:true,active:'prod'}),/^Applied/);
assert.equal(net.storagePaths(store).length,2);last.unplugged=true;assert.equal(net.storagePaths(store).length,1);last.unplugged=false;fb.net.product.fabric.enabled=false;assert.equal(net.storagePaths(store).length,1);fb.net.product.fabric.enabled=true;
// Same switch cannot count as two independent failure domains.
links[2].b=fa.id;links[3].a=fa.id;fa.net.product.fabric.members.push(ids.wwpnB,target.wwpnB);assert.equal(net.storagePaths(store).length,1);links[2].b=fb.id;links[3].a=fb.id;
links.length=0;for(const n of nodes)for(const p of n.ports)delete p.link;
store.spec.sku='me5024iscsi';const iscsi={...base,protocol:'iSCSI',portA:'DATA-A',portB:'DATA-B',ipA:'172.16.10.10',ipB:'172.16.11.10',prefix:24,vlanA:3000,vlanB:3001,iqn:ids.iqn};assert.match(cfg(host,'host',iscsi),/^Applied/);assert.match(cfg(store,'storage',{...iscsi,ipA:'172.16.10.20',ipB:'172.16.11.20',pool:'POOL',mode:'Virtual',raid:'ADAPT',volume:'VOL2',sizeGiB:100,host:host.id,initiator:ids.iqn}),/^Applied/);
for(const [sw,vlan]of [[ea,3000],[eb,3001]])for(const p of sw.ports)Object.assign(p.cfg,{access:vlan,mtu:1500});link(store,2,ea,2);link(ea,3,host,2);link(store,3,eb,2);link(eb,3,host,3);assert.equal(net.storagePaths(store).length,2);eb.ports[2].cfg.mtu=9000;assert.equal(net.storagePaths(store).length,1);eb.ports[2].cfg.mtu=1500;eb.ports[2].cfg.access=1;assert.equal(net.storagePaths(store).length,1);eb.ports[2].cfg.access=3001;host.net.product.host.ipB='172.16.12.10';assert.equal(net.storagePaths(store).length,1);host.net.product.host.ipB='172.16.11.10';assert.equal(net.storagePaths(store).length,2);
// NVMe/TCP must validate NQN registration as well as the two data paths.
store.spec.sku='powerstore';store.model='PowerStore';const nvme={...iscsi,protocol:'NVMe/TCP',iqn:'nqn.2014-08.org.nvmexpress:host-training'};
assert.match(cfg(host,'host',nvme),/^Applied/);assert.match(cfg(store,'storage',{...nvme,ipA:'172.16.10.20',ipB:'172.16.11.20',pool:'POOL',volume:'NVME1',sizeGiB:100,host:host.id,initiator:nvme.iqn}),/^Applied/);
assert.equal(net.storagePaths(store).length,2);host.net.product.host.iqn='nqn.2014-08.org.nvmexpress:wrong-host';assert.equal(net.storagePaths(store).length,0);host.net.product.host.iqn=nvme.iqn;
store.spec.sku='me5024iscsi';assert.match(cfg(store,'storage',{...store.net.product.storage}),/controller option/);store.spec.sku='powerstore';
fw.net.ispContract={id:'ISP-1',ip:'203.0.113.2',gateway:'203.0.113.1'};const wan={port:'DATA-A',mode:'DHCP',dns:'1.1.1.1',enabled:true,defaultRoute:true};assert.match(cfg(fw,'wan',wan),/^Applied/);assert(net.wanStatus(fw).ok);const test=()=>cfg(fw,'internet-test',{lan:'DATA-B'});assert.match(test(),/LAN interface/);net.apply({type:'enterprise',node:fw.id,op:'interface-address',index:3,ip:'192.168.20.1',prefix:24});assert.match(test(),/cable/);link(fw,3,ea,4);assert.match(test(),/DENY/);net.apply({type:'enterprise',node:fw.id,op:'policy',value:{id:1,srcintf:'DATA-B',dstintf:'DATA-A',action:'accept',nat:false}});assert.match(test(),/NAT/);net.apply({type:'enterprise',node:fw.id,op:'policy',value:{id:1,srcintf:'DATA-B',dstintf:'DATA-A',action:'accept',nat:true}});assert.match(test(),/^PASS/);fw.net.enterprise.routes=[];assert(!net.wanStatus(fw).ok);console.log('PASS: FC zoning, dual fabric failure domains, link loss; iSCSI and NVMe/TCP initiator/subnet/VLAN/MTU paths; WAN DHCP handoff, LAN cable, implicit deny, source NAT and default route validation.');
