// LAN room: the authoritative shared world, HTTP API, server-sent world frames and campaign autosave.
// Used by `node lan/server.mjs` (web package) and in-process by the desktop app (Electron main).
import http from 'node:http';
import {readFile,stat,writeFile,rename,copyFile,mkdir} from 'node:fs/promises';
import {fileURLToPath,pathToFileURL} from 'node:url';
import path from 'node:path';
import os from 'node:os';
import {randomBytes} from 'node:crypto';
const here=path.dirname(fileURLToPath(import.meta.url));
// options: { port=8080, bind='0.0.0.0', savePath, roomCode, hostKey, deliveryScale, log, error }
export async function startRoom(options={}){
const log=options.log||console.log,logError=options.error||console.error;
const project=path.resolve(here,'..');
const root=await stat(path.join(project,'dist','index.html')).then(()=>path.join(project,'dist')).catch(()=>project);
const {RACK_PADS,ROOM,CASINO}=await import(pathToFileURL(path.join(root,'facility-layout.js')));
const {redactCasino}=await import(pathToFileURL(path.join(root,'casino-logic.js')));
// Each engineer's copy of the world: other players' poker hole cards (and the blackjack hole card) stay hidden.
const viewFor=(base,p)=>base.operations?.casino?{...base,operations:{...base.operations,casino:redactCasino(base.operations.casino,p?.name)}}:base;
const {modelForSKU}=await import(pathToFileURL(path.join(root,'enterprise-models.js')));
const {hostActionError,EMOTE_IDS,FACE_IDS,SKIN_IDS,HAT_IDS,OUTFIT_IDS,CARRY_IDS,cleanName}=await import(pathToFileURL(path.join(root,'play-rules.js')));
const {physicalOffline,physicalLinkDown,CATALOG}=await import(pathToFileURL(path.join(root,'operations.js')));
const {createNetwork}=await import(pathToFileURL(path.join(root,'network-sim.js')));
const {createSharedWorld}=await import(pathToFileURL(path.join(root,'shared-world.js')));
const seed=JSON.parse(await readFile(path.join(here,'world.json'),'utf8'));
const seedHub=seed.nodes.find(n=>n.id==='MGMT-SW');if(seedHub.ports.length===54){seedHub.ports.slice(0,52).forEach((p,i)=>p.name='MGMT-'+(i+2));seedHub.ports.splice(52,0,{name:'MGMT-1',speed:1,medium:'Ethernet',side:'rear',pos:{x:0,y:0,z:-1.472}});seedHub.net.ports.splice(52,0,{admin:true,mode:'access',access:70,allowed:[1,70]});}
const nodes=seed.nodes,byId=Object.fromEntries(nodes.map(n=>[n.id,n])),state={...seed.faults,pending:false},links=[];
for(const n of nodes)n.ports.forEach((p,i)=>{p.cfg=n.net.ports[i];p.link=null;});
function connect(a,b,kind,tag,speed,[pa,pb]){const l={a,b,kind,tag,speed,pa,pb,unplugged:false};links.push(l);pa.link=l;pb.link=l;return l;}
for(const c of seed.cables)connect(c.a,c.b,c.kind,c.tag,c.speed,[byId[c.a].ports[c.pa],byId[c.b].ports[c.pb]]);
const isOffline=n=>physicalOffline(n)||!!(state.site&&n.site==='primary'||state.controller&&n.id==='CONTROLLER-A'||state.san&&n.id==='SAN-A');
function refreshFaults(){for(const l of links)l.disabled=physicalLinkDown(l,byId)||!!l.unplugged||l.pa.cfg?.admin===false||l.pb.cfg?.admin===false||isOffline(byId[l.a])||isOffline(byId[l.b])||!!(state.link&&l.tag==='uplink-02')||!!(state.san&&l.tag==='path-a')||!!(l.tag==='dr-ingress'&&!state.site);}
function spawn(spec){if(byId[spec.id])return byId[spec.id];const c=CATALOG.find(c=>c.id===spec.sku);if(!c)throw Error('Invalid equipment');const pad=RACK_PADS.find(p=>p.rack===spec.rack);const rackX=pad?.x??{R01:-9,R02:-3,R03:3,R04:9,R05:22,R06:28}[spec.rack];if(rackX===undefined)throw Error('Invalid rack');const template=seed.nodes.find(n=>n.type===spec.type&&!n.controller&&n.id!=='MGMT-SW');const n={...structuredClone({...template,ports:[],net:undefined}),...spec,spec,pos:{x:rackX,y:.55+(spec.unit-1)*.267+(spec.units*.267-.025)/2,z:(pad?.z||0)+3-(['switch','san','isp'].includes(spec.type)?2.8:spec.type==='gpu'?6:4.5)/2},site:['R05','R06'].includes(spec.rack)?'dr':'primary'};const port=(name,speed=25,medium='Ethernet',service=false)=>({name,speed,medium,service,link:null});if(spec.type==='switch')n.ports=[...Array.from({length:48},(_,i)=>port('1/1/'+(i+1))),...Array.from({length:4},(_,i)=>port('1/1/'+(i+49),100))];else if(spec.type==='san')n.ports=Array.from({length:24},(_,i)=>port('FC '+(i+1),32,'Fibre Channel'));else if(spec.type==='firewall')n.ports=[...Array.from({length:16},(_,i)=>port(String(i+1))),...Array.from({length:12},(_,i)=>port(String(i+17),100)),...['HA1','HA2','AUX1','AUX2'].map(k=>port(k))];else n.ports=[port('NIC-1'),port('NIC-2'),port('HBA-A',32,'Fibre Channel'),port('HBA-B',32,'Fibre Channel'),port('MGMT',1),port('DATA-1',100),port('DATA-2',100)];const profile=modelForSKU(spec.sku);if(profile?.portLayout)n.ports=profile.portLayout.map(p=>port(p.name,p.speed,p.medium));n.ports.push({...port('MGMT UPLINK',1),alias:profile?.vendor==='Cisco'?'mgmt0':profile?.vendor==='Fortinet'?'mgmt':'mgmt1/1/1'});if(['switch','san','firewall'].includes(spec.type))n.ports.push(port('CONSOLE',0,'Console',true));n.ports.push(port('SERVICE LAN',1,'Ethernet',true));if(spec.sku==='switch24')n.ports.slice(24,48).forEach(p=>p.reserved=true);if(spec.sku==='mgmt')n.ports.filter(p=>!p.service).forEach(p=>p.speed=1);if(spec.sku==='core')n.ports.filter(p=>!p.service&&p.name!=='MGMT UPLINK').forEach(p=>p.speed=100);if(spec.sku==='san64')n.ports.filter(p=>!p.service&&p.name!=='MGMT UPLINK').forEach(p=>p.speed=64);nodes.push(n);byId[n.id]=n;return n;}
const ctx={spawn,addRack:()=>{},nodes,links,byId,state,connect,refreshFaults,isOffline};const network=createNetwork(ctx),world=createSharedWorld(ctx,network);refreshFaults();
const campaignPath=options.savePath||path.join(project,'lan','campaign-save.json');await mkdir(path.dirname(campaignPath),{recursive:true}).catch(()=>{});let persistQueue=Promise.resolve();
if(options.deliveryScale!==undefined)globalThis.INFRA_DELIVERY_SCALE=Math.max(0,Number(options.deliveryScale)||0);
try{const saved=JSON.parse(await readFile(campaignPath,'utf8'));if((saved.format||0)<32){const backup=campaignPath.replace(/\.json$/,'')+'.pre-v32-backup.json';await copyFile(campaignPath,backup);log('Older campaign save backed up to '+backup+' before migration');}if(saved.operations?.mode==='campaign'&&!saved.operations.payday){for(const s of saved.operations.stock){if(s.holders.length&&!s.floor)s.floor={x:-38,z:3};s.holders=[];};world.restore(saved)};}catch(e){if(e.code!=='ENOENT')logError('Campaign save could not be loaded:',e.message);}
// Payday mode has its own save file next to the campaign save; neither ever overwrites the other.
const paydayPath=path.join(path.dirname(campaignPath),'payday-save.json');
try{const pay=JSON.parse(await readFile(paydayPath,'utf8'));if(pay.operations?.payday){for(const s of pay.operations.stock||[]){if(s.holders?.length&&!s.floor)s.floor={x:-38,z:3};s.holders=[];}world.operations.stash('payday',pay);}}catch(e){if(e.code!=='ENOENT')logError('Payday save could not be loaded:',e.message);}
function persist(){if(world.operations.game.mode!=='campaign')return;const target=world.operations.game.payday?paydayPath:campaignPath,data=JSON.stringify(world.snapshot());persistQueue=persistQueue.then(async()=>{await writeFile(target+'.tmp',data);await rename(target+'.tmp',target);}).catch(e=>logError('Campaign autosave failed:',e.message));return persistQueue;}
const players=new Map();let revision=0,actionQueue=Promise.resolve(),mutating=false;const events=[];let port=Number(options.port??8080),host=options.bind||'0.0.0.0';
function lanAddresses(){const out=[];try{for(const list of Object.values(os.networkInterfaces()))for(const i of list??[])if(i.family==='IPv4'&&!i.internal)out.push(i.address+':'+(server?.address()?.port||port));}catch{}return out;}
// The room code is kept next to the save, so guests can rejoin after a host restart with the same code.
const roomFile=campaignPath.replace(/\.json$/,'')+'.room';const roomCode=options.roomCode||await readFile(roomFile,'utf8').then(x=>x.trim()).catch(()=>'')||randomBytes(3).toString('hex').toUpperCase();if(!options.roomCode)await writeFile(roomFile,roomCode).catch(()=>{});
const hostKey=options.hostKey||randomBytes(24).toString('hex');
const loopback=req=>['127.0.0.1','::1','::ffff:127.0.0.1'].includes(req.socket.remoteAddress);
const json=(res,status,value)=>{res.writeHead(status,{'Content-Type':'application/json','Cache-Control':'no-store'});res.end(JSON.stringify(value));};
const roster=()=>[...players.values()].map(p=>({id:p.id,name:p.name,role:p.role,color:p.color,slot:[0x6bd9ff,0xffc875,0xaf98ff,0x82e5aa,0xff879e,0xe2e779,0x7ca1ff,0xc5a27d,0x94d8d3,0xe19df5,0xe2b7a5,0xb4c4d4].indexOf(p.color),pose:p.pose}));
function send(p,type,data){if(!p.stream)return;if(p.stream.writableLength>2000000){p.stream.destroy();p.stream=null;return;}p.stream.write(`event: ${type}\ndata: ${JSON.stringify(data)}\n\n`);}
function broadcast(type,data){const frame=`event: ${type}\ndata: ${JSON.stringify(data)}\n\n`;for(const p of players.values()){if(!p.stream)continue;if(p.stream.writableLength>2000000){p.stream.destroy();p.stream=null;continue;}p.stream.write(frame);}}
function worldEvent(message){events.unshift(message);events.length=Math.min(events.length,8);const base=world.snapshotFor();for(const p of players.values())send(p,'world',{revision,world:viewFor(base,p),events});}
function remove(id){const p=players.get(id);if(!p)return;p.stream?.end();players.delete(id);let changed=false;for(const s of world.operations.game.stock){if(s.holders.includes(p.id)){s.holders=s.holders.filter(id=>id!==p.id);s.floor={x:p.pose.x,z:p.pose.z};changed=true;}}if(changed){revision++;worldEvent('Carried equipment released after engineer left');persist();}broadcast('players',roster());}
async function body(req){let length=0,chunks=[];for await(const chunk of req){length+=chunk.length;if(length>32768)throw new Error('Request too large');chunks.push(chunk);}return JSON.parse(Buffer.concat(chunks).toString()||'{}');}
const server=http.createServer(async(req,res)=>{try{
 const url=new URL(req.url,'http://'+req.headers.host);if(req.headers.origin&&req.headers.origin!=='http://'+req.headers.host){json(res,403,{error:'Use this server address directly'});return;}
 if(url.pathname==='/api/room'&&req.method==='GET'){const localHost=loopback(req)&&![...players.values()].some(p=>p.isHost);json(res,200,{protocol:'infra-lan-v1',players:players.size,maxPlayers:12,localHost,...localHost?{roomCode,hostKey,addresses:lanAddresses()}:{},...loopback(req)?{campaign:world.operations.campaignSummary(),payday:world.operations.paydaySummary()}:{}});return;}
 if(url.pathname==='/api/players-check'&&req.method==='GET'){json(res,players.has(url.searchParams.get('token'))?200:401,{ok:players.has(url.searchParams.get('token'))});return;}
 if(url.pathname==='/api/join'&&req.method==='POST'){const data=await body(req);if(data.code!==roomCode){json(res,403,{error:'Incorrect room code. Ask the host.'});return;}if(players.size>=12){json(res,409,{error:'Room full (12/12).'});return;}const isHost=typeof data.hostKey==='string'&&data.hostKey===hostKey;if(data.hostKey&&!isHost){json(res,403,{error:'Incorrect host key. Guests should leave it empty.'});return;}if(isHost&&[...players.values()].some(p=>p.isHost)){json(res,409,{error:'The host is already connected.'});return;}const token=randomBytes(16).toString('hex'),id=randomBytes(8).toString('hex'),used=new Set([...players.values()].map(p=>p.color)),color=[0x6bd9ff,0xffc875,0xaf98ff,0x82e5aa,0xff879e,0xe2e779,0x7ca1ff,0xc5a27d,0x94d8d3,0xe19df5,0xe2b7a5,0xb4c4d4].find(c=>!used.has(c));const p={id,token,isHost,role:'field',name:cleanName(data.name),color,pose:{x:-3+players.size*2,y:9.7,z:11,yaw:0,crouched:false,active:false},seen:Date.now(),stream:null,count:0,window:Date.now()};players.set(token,p);json(res,200,{id,token,isHost,revision,world:viewFor(world.snapshotFor(),p),players:roster(),events});broadcast('players',roster());return;}
 if(url.pathname.startsWith('/api/')){const id=req.headers['x-player-token']||url.searchParams.get('token'),p=players.get(id);if(!p){json(res,401,{error:'Join the room first.'});return;}p.seen=Date.now();if(Date.now()-p.window>1000){p.window=Date.now();p.count=0;}if(++p.count>35){json(res,429,{error:'Too many updates'});return;}
 if(url.pathname==='/api/events'&&req.method==='GET'){p.stream?.end();res.writeHead(200,{'Content-Type':'text/event-stream','Cache-Control':'no-cache','Connection':'keep-alive','X-Accel-Buffering':'no'});res.write(': connected\n\n');p.stream=res;send(p,'players',roster());send(p,'world',{revision,world:viewFor(world.snapshotFor(),p),events});res.on('close',()=>{if(p.stream===res)p.stream=null;});return;}
 if(url.pathname==='/api/name'&&req.method==='POST'){const d=await body(req);p.name=cleanName(d.name);broadcast('players',roster());json(res,200,{ok:true,name:p.name});return;}
 if(url.pathname==='/api/role'&&req.method==='POST'){const d=await body(req);if(!['field','operations'].includes(d.role))throw Error('Unknown engineer role');p.role=d.role;broadcast('players',roster());json(res,200,{ok:true});return;}
 if(url.pathname==='/api/chat'&&req.method==='POST'){const d=await body(req);if(typeof d.text!=='string'||!d.text.trim()||d.text.length>200)throw Error('Message must contain 1–200 characters');if(Date.now()-(p.lastChat||0)<700)throw Error('Please wait before sending another message');p.lastChat=Date.now();broadcast('chat',{player:p.id,name:'ENGINEER-0'+([0x6bd9ff,0xffc875,0xaf98ff,0x82e5aa,0xff879e,0xe2e779,0x7ca1ff,0xc5a27d,0x94d8d3,0xe19df5,0xe2b7a5,0xb4c4d4].indexOf(p.color)+1),color:p.color,text:d.text.trim(),at:Date.now()});json(res,200,{ok:true});return;}
 if(url.pathname==='/api/ping'&&req.method==='POST'){const d=await body(req);if(!['x','y','z'].every(k=>Number.isFinite(d[k]))||d.x<ROOM.minX||d.x>ROOM.maxX||d.y<0||d.y>88||d.z<ROOM.minZ||d.z>ROOM.maxZ)throw Error('Invalid ping location');if(Date.now()-(p.lastPing||0)<800)throw Error('Please wait before another ping');p.lastPing=Date.now();const n=byId[d.node],port=n?.ports[d.port];const label=n&&n.active!==false?n.id+(port?' / '+port.name:''):/^R(?:0[1-9]|1[0-9]|20)$/.test(d.rack||'')?d.rack:'LOCATION';broadcast('ping',{player:p.id,name:'ENGINEER-0'+([0x6bd9ff,0xffc875,0xaf98ff,0x82e5aa,0xff879e,0xe2e779,0x7ca1ff,0xc5a27d,0x94d8d3,0xe19df5,0xe2b7a5,0xb4c4d4].indexOf(p.color)+1),color:p.color,label,x:d.x,y:d.y,z:d.z});json(res,200,{ok:true});return;}
 if(url.pathname==='/api/pose'&&req.method==='POST'){const d=await body(req),v=d.pose;if(!v||!['x','y','z','yaw'].every(k=>Number.isFinite(v[k]))){json(res,400,{error:'Invalid pose'});return;}p.pose={x:Math.max(ROOM.minX+1,Math.min(ROOM.maxX-1,v.x)),y:Math.max(1,Math.min(80,v.y)),z:Math.max(ROOM.minZ+1,Math.min(Math.max(ROOM.maxZ,CASINO?.maxZ??0)-1,v.z)),yaw:v.yaw%(Math.PI*2),crouched:!!v.crouched,active:!!v.active,laptop:!!v.laptop,face:FACE_IDS.includes(v.face)?v.face:'cute',skin:SKIN_IDS.includes(v.skin)?v.skin:'yellow',hat:HAT_IDS.includes(v.hat)?v.hat:'cap',outfit:OUTFIT_IDS.includes(v.outfit)?v.outfit:'bands',carry:CARRY_IDS.includes(v.carry)?v.carry:null,point:!!v.point,gun:!!v.gun&&/^\s*darja\s*$/i.test(p.name||''),shot:{n:Number.isInteger(v.shot?.n)?v.shot.n%1e9:0,pitch:Number.isFinite(v.shot?.pitch)?Math.max(-1.5,Math.min(1.5,v.shot.pitch)):0},emote:{id:EMOTE_IDS.includes(v.emote?.id)?v.emote.id:null,n:Number.isInteger(v.emote?.n)?v.emote.n%1e9:0}};json(res,200,{ok:true});return;}
 if(url.pathname==='/api/action'&&req.method==='POST'){const d=await body(req);const previous=actionQueue;let release;actionQueue=new Promise(resolve=>release=resolve);await previous;mutating=true;try{if(d.revision!==revision){json(res,409,{error:'World changed; retry your command.',revision,world:viewFor(world.snapshotFor(),p),events});return;}const action=d.action;if(!action||typeof action!=='object'){json(res,400,{error:'Invalid action'});return;}const denied=hostActionError(p.isHost,action);if(denied){json(res,403,{error:denied});return;}const result=await world.apply(action,p.id,roster(),{isHost:p.isHost});const message=typeof result==='string'?result:result.message||result.reason||'Office state updated';revision++;await persist();worldEvent(p.name+': '+message);json(res,200,{message,result,revision,world:viewFor(world.snapshotFor(),p),events});return;}finally{mutating=false;release();}}
 if(url.pathname==='/api/leave'&&req.method==='POST'){remove(p.token);json(res,200,{ok:true});return;}json(res,404,{error:'Not found'});return;
 }
 if(req.method!=='GET'&&req.method!=='HEAD'){res.writeHead(405);res.end();return;}const pathname=decodeURIComponent(url.pathname);if(pathname.startsWith('/lan/')){res.writeHead(403);res.end();return;}const file=path.resolve(root,'.'+(pathname==='/'?'/index.html':pathname));if(!file.startsWith(root+path.sep)||pathname.split('/').some(s=>s.startsWith('.'))){res.writeHead(403);res.end();return;}const ext=path.extname(file);const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.png':'image/png','.glb':'model/gltf-binary','.txt':'text/plain','.json':'application/json'}[ext];if(!mime){res.writeHead(404);res.end();return;}const info=await stat(file);if(!info.isFile()){res.writeHead(404);res.end();return;}res.writeHead(200,{'Content-Type':mime,'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'});res.end(req.method==='HEAD'?undefined:await readFile(file));
 }catch(e){if(!res.headersSent)json(res,e.code==='ENOENT'?404:400,{error:e.message});else res.end();}});
let lastRosterJSON='';let lastOperationsTick=0;const tick=setInterval(()=>{if(Date.now()-lastOperationsTick>1000){lastOperationsTick=Date.now();if(!mutating&&[world.operations.tick(),world.office.tick()].some(Boolean)){revision++;worldEvent('Facility state updated');persist();}} for(const p of players.values())if(Date.now()-p.seen>30000)remove(p.token);const list=roster(),encoded=JSON.stringify(list);if(encoded!==lastRosterJSON){lastRosterJSON=encoded;broadcast('players',list);}},100);
// The world tick runs for the room's lifetime; rebind() closes and reopens only the listener.
function listen(p,b){return new Promise((resolve,reject)=>{const fail=e=>{server.off('listening',ok);reject(e);},ok=()=>{server.off('error',fail);resolve(server.address().port);};server.once('error',fail);server.once('listening',ok);server.listen(p,b);});}
port=await listen(port,host);
const api={get port(){return port;},get bind(){return host;},roomCode,hostKey,world,addresses:lanAddresses,get players(){return players.size;},savePath:campaignPath,
 // Switch between local-only (127.0.0.1) and LAN hosting (0.0.0.0) without losing the world. Connected
 // clients reconnect on their own (their SSE stream drops and the client rejoins).
 async rebind(bind,newPort=port){for(const p of players.values())p.stream?.end();await new Promise(r=>server.close(()=>r()));server.closeAllConnections?.();host=bind;port=await listen(newPort,bind);return port;},
 async close(){clearInterval(tick);for(const p of players.values())p.stream?.end();await persistQueue;await new Promise(r=>server.close(()=>r()));server.closeAllConnections?.();}};
return api;
}
